name: OpenAPI Sync Action
description: Sync repository with remote OpenAPI specification file
inputs:
  openapi-url:
    description: "URL to the OpenAPI spec file"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Sync OpenAPI specs"
      id: sync
      shell: bash
      run: |
        if test -f "openapi.yaml"
        then
            curl -o openapi.yaml~ ${{ inputs.openapi-url }}
            if ! cmp -s openapi.yaml openapi.yaml~
            then
                rm openapi.yaml
                mv openapi.yaml~ openapi.yaml
                echo Updated openapi.yaml
            else
                rm openapi.yaml~
                echo No update available
            fi
        else
            curl -o openapi.yaml ${{ inputs.openapi-url }}
        fi
