on:
  push:
    branches: [ "main" ]
jobs:
    create_latest_tag:
      name: "Create latest tag"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run latest-tag
          uses: EndBug/latest-tag@latest
          with:
            description: Update to latest version