on: [push]

jobs:
  test_openapi_sync_action:
    runs-on: ubuntu-latest
    name: Test openapi-sync-action
    steps:
      - uses: actions/checkout@v3
      - uses: maximiliancw/hello-world-composite-action@latest
        with:
          openapi-url: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml'
          # openapi-url: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/api-with-examples.yaml'
